version: '3.9'

services:
  app:
    build: .
    container_name: multi-repo-qa
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./indices:/app/indices
      - ./.env:/app/.env
    restart: unless-stopped

volumes:
  data:
  indices:

